id: ADC3DCFCE
base_file: fC77C.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 22:53:56.524372
  last_modified_at: 2022-05-30 22:53:56.524383
